### ISSUE TITLE
Acala indexer fails - BlockDispatcherService ERROR Failed to fetch blocks from queue 

### ISSUE THREAD

**Issue by mcf-rocks** [AcalaNetwork/bodhi.js#620] opened 2022-12-29 16:23 UTC
requires node 1.17.0 (?)
```
acala@x4:~/bodhi.js/evm-subql$ DB_USER=postgres DB_PASS=xxxxx DB_DATABASE=acala DB_HOST=localhost DB_PORT=5432 yarn index 
yarn run v1.22.19
$ subql-node -f ./project.yaml --batch-size 30 --db-schema acala_evm --log-level debug --port 4040 --unsafe
2022-12-29T16:22:01.579Z <subql-node> WARN UNSAFE MODE IS ENABLED. This is not recommended for most projects and will not be supported by our hosted service 
**2022-12-29T16:22:01.712Z <configure> ERROR Create Subquery project from given path failed! 
Error: Runner require node version 1.17.0, current node 1.7.0**
    at loadProjectFromManifest1_0_0 (/home/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/dist/configure/SubqueryProject.js:87:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ```

**Comment by mcf-rocks** [comment] 2022-12-29 16:43
but with 1.17.0 installed:
```
acala@x4:~/bodhi.js/evm-subql$ DB_USER=postgres DB_PASS=applesandpearsheaven DB_DATABASE=acala DB_HOST=localhost DB_PORT=5432 yarn index 
yarn run v1.22.19
$ subql-node -f ./project.yaml --batch-size 30 --db-schema acala_evm --log-level debug --port 4040 --unsafe
2022-12-29T16:42:48.681Z <subql-node> INFO Current @subql/node version is 1.17.0 
2022-12-29T16:42:48.682Z <subql-node> WARN UNSAFE MODE IS ENABLED. This is not recommended for most projects and will not be supported by our hosted service 
2022-12-29T16:42:48.874Z <indexer> INFO indexer manager start 
2022-12-29 16:42:49        REGISTRY: Unknown signed extensions SetEvmOrigin found, treating them as no-effect
2022-12-29T16:42:49.153Z <store> INFO Historical state is disabled 
2022-12-29T16:42:49.239Z <dictionary> WARN failed to fetch specVersion result 
Error: Only absolute URLs are supported
    at new ApolloError (/home/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@apollo/client/errors/errors.cjs:34:28)
    at /home/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@apollo/client/core/core.cjs:1595:19
    at both (/home/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@apollo/client/utilities/utilities.cjs:986:53)
    at /home/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@apollo/client/utilities/utilities.cjs:979:72
    at new Promise (<anonymous>)
    at Object.then (/home/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@apollo/client/utilities/utilities.cjs:979:24)
    at Object.error (/home/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@apollo/client/utilities/utilities.cjs:987:49)
    at notifySubscription (/home/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/home/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/home/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/zen-observable/lib/Observable.js:240:7)
2022-12-29T16:42:49.242Z <subql-node> INFO Node started on port: 4040 
2022-12-29T16:42:49.246Z <BlockDispatcherService> INFO Enqueueing blocks 2611615...2611644, total 30 blocks 
2022-12-29T16:42:49.246Z <BlockDispatcherService> INFO fetch block [2611615,2611644], total 30 blocks 
2022-12-29T16:42:49.246Z <BlockDispatcherService> INFO Enqueueing blocks 2611645...2611674, total 30 blocks 
2022-12-29T16:42:49.246Z <BlockDispatcherService> INFO Enqueueing blocks 2611675...2611704, total 30 blocks 
2022-12-29T16:42:49.247Z <BlockDispatcherService> INFO Enqueueing blocks 2611705...2611734, total 30 blocks 
2022-12-29T16:42:49.343Z <fetch> ERROR failed to fetch events at block 0xdcdd89927d8a348e00257e1ecc8617f45edb5118efff3ea2f9961b2ad9b7690a 
2022-12-29T16:42:49.343Z <fetch> ERROR failed to fetch events at block 0xdcdd89927d8a348e00257e1ecc8617f45edb5118efff3ea2f9961b2ad9b7690a 
2022-12-29T16:42:49.343Z <BlockDispatcherService> ERROR Failed to fetch blocks from queue 
Error: Unable to retrieve header and parent from supplied hash
    at ApiPromise._getBlockRegistryViaHash (/home/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@polkadot/api/cjs/base/Init.js:213:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
error Command failed with exit code 1.
```

**Comment by shunjizhan** [comment] 2023-01-03 03:10
`Unable to retrieve header and parent from supplied hash` is sometimes caused by network issue, can you try again with an extra flag `--disable-historical`?

**Comment by shunjizhan** [comment] 2023-01-03 03:18
by the way it's recommended to run production subql with docker, running `yarn index` is usually for testing purpose. Feel free to try out docker setup ([doc](https://github.com/AcalaNetwork/bodhi.js/tree/master/evm-subql#for-production))

**Comment by mcf-rocks** [comment] 2023-01-03 18:18
tried that flag, but same issue... i am currently also trying to run the docker images... it would be much better if it worked from source code, because with docker images, i have no idea what it is running.

**Comment by shunjizhan** [comment] 2023-01-04 04:19
the blockhash from error msg is odd... `0xdcdd89927d8a348e00257e1ecc8617f45edb5118efff3ea2f9961b2ad9b7690a` doesn't exit in Acala...

Are you reusing the db schema `acala_evm` that's used before with old version indexer? Can you try using a new clean schema with the following steps:
1) update bodhi.js to latest master
2) `cd evm-subql && yarn && rm -rf dist/ && yarn build`
3) `subql-node -f ./project.yaml --batch-size 30 --db-schema acala_evm_new_clean --log-level debug --port 4040 --unsafe --disable-historical`

**Comment by shunjizhan** [comment] 2023-01-05 02:57
@mcf-rocks hey mate actually we encountered similar issue, and the issue was resolved by simply restarting `subql-node`

**Comment by mcf-rocks** [comment] 2023-01-06 12:11
did what you said with a new schema, worked for a while, but them again
```
Jan 06 12:09:00 x3 yarn[2107360]: 2023-01-06T12:09:00.416Z <subql-node> INFO Node started on port: 4040
Jan 06 12:09:00 x3 yarn[2107360]: 2023-01-06T12:09:00.420Z <BlockDispatcherService> INFO Enqueueing blocks 2611616...2611645, total 30 blocks
Jan 06 12:09:00 x3 yarn[2107360]: 2023-01-06T12:09:00.420Z <BlockDispatcherService> INFO fetch block [2611616,2611645], total 30 blocks
Jan 06 12:09:00 x3 yarn[2107360]: 2023-01-06T12:09:00.421Z <BlockDispatcherService> INFO Enqueueing blocks 2611646...2611675, total 30 blocks
Jan 06 12:09:00 x3 yarn[2107360]: 2023-01-06T12:09:00.421Z <BlockDispatcherService> INFO Enqueueing blocks 2611676...2611705, total 30 blocks
Jan 06 12:09:00 x3 yarn[2107360]: 2023-01-06T12:09:00.421Z <BlockDispatcherService> INFO Enqueueing blocks 2611706...2611735, total 30 blocks
Jan 06 12:09:00 x3 yarn[2107360]: 2023-01-06T12:09:00.514Z <fetch> ERROR failed to fetch events at block 0xdcdd89927d8a348e00257e1ecc8617f45edb5118efff3ea2f9961b2ad9b7690a
Jan 06 12:09:00 x3 yarn[2107360]: 2023-01-06T12:09:00.514Z <fetch> ERROR failed to fetch events at block 0xdcdd89927d8a348e00257e1ecc8617f45edb5118efff3ea2f9961b2ad9b7690a
Jan 06 12:09:00 x3 yarn[2107360]: 2023-01-06T12:09:00.514Z <fetch> ERROR failed to fetch events at block 0xdcdd89927d8a348e00257e1ecc8617f45edb5118efff3ea2f9961b2ad9b7690a
Jan 06 12:09:00 x3 yarn[2107360]: 2023-01-06T12:09:00.515Z <BlockDispatcherService> ERROR Failed to fetch blocks from queue
Jan 06 12:09:00 x3 yarn[2107360]: Error: Unable to retrieve header and parent from supplied hash
Jan 06 12:09:00 x3 yarn[2107360]:     at ApiPromise._getBlockRegistryViaHash (/home/acala/node-v16.15.0-linux-x64/lib/node_modules/@subql/node/node_modules/@polkadot/api/cjs/base/Init.js:213:13)
Jan 06 12:09:00 x3 yarn[2107360]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Jan 06 12:09:00 x3 yarn[2107360]:     at runNextTicks (node:internal/process/task_queues:65:3)
Jan 06 12:09:00 x3 yarn[2107360]:     at processImmediate (node:internal/timers:437:9)
Jan 06 12:09:00 x3 yarn[2107338]: error Command failed with exit code 1.

```

**Comment by shunjizhan** [comment] 2023-01-06 12:23
> is my Acala blockchain data corrupt
Your data is fine. That hash might be the empty block hash, looks like a bug in subquery, see https://github.com/subquery/subql/issues/1481

> @mcf-rocks hey mate actually we encountered similar issue (at different block), and the issue was resolved by simply restarting subql-node
can you try restart the indexer?

**Comment by mcf-rocks** [comment] 2023-01-06 12:39
I have restarted often, same result.

**Comment by shunjizhan** [comment] 2023-01-12 01:44
Did you fully stopped indexer before restarting? i.e. `docker ps -a` doesn’t show the indexer anymore. 

We used AWS ECS which basically removes the whole container and create a new one, which worked. So if restarting doesn’t work I suspect it’s not a “full restart”

**Comment by mcf-rocks** [comment] 2023-01-12 19:58
> Please also switch to this endpoint `wss://karura-rpc.dwellir.com/`

why? shouldn't i use my own node?

also, that says "karura", I'm trying to index acala.

**Comment by shunjizhan** [comment] 2023-01-13 02:35
> shouldn't i use my own node?
oooops sorry for the confusion, you should use your own node.

> `docker ps -a` doesn’t show the indexer anymore
Did a "full restart" help?

**Comment by shunjizhan** [comment] 2023-01-13 03:28
hey, after some more experiment, we found that the solution is "restarting with different endpoint", it's magic and subquery team is investigating the root cause.

Could you try switch endpoint for like 20 sec (just to bypass the erro), and switch back to your own endpoint then?

**Comment by mcf-rocks** [comment] 2023-01-13 19:59
The switching thing worked.

**Closed** 2023-01-15 05:56 UTC
